import sys, os
import pandas as pd
from snakemake.utils import min_version

min_version("6.14.0")

configfile: 'config/config.yaml'

shell.prefix("""
    
     """)

def targets_input():
    L = []
    L.append('results/workflow.svg')
    L.append('results/fastqc/multiqc_report.html')

    return (L)

rule targets:
    input: 
        targets_input()
    resources: 
        mem_mb=lambda wildcards, attempt: attempt * 1000 

include: 'rules/create_dag.smk'
include: 'rules/fastqc.smk'

