# Analysis Params
SAMPLES:
    - Lrig1
    - WT_RSmad7

# GENOME
GENOME: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/mm10.ucsc.fa
GTF: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/gencode.vM25.primary_assembly.annotation.gtf
GSIZE: "mm"  # MACS2 gsize param, hs, mm, ce, dm, 2.7e8
SizeFile: "/project/umw_mccb/genome/Mus_musculus_UCSC_mm10/star_idx/chrNameLength.txt" # for bedGraphToBigWig

# TRIMMING
TRIMMOMATIC: 'ILLUMINACLIP:resources/adapters/TruSeq3-PE.fa:2:30:10 LEADING:10 TRAILING:10 SLIDINGWINDOW:4:15 MINLEN:24'

# MAPPING
BOWTIE2: '--sensitive'
filter: 'BEGIN{FS=OFS="\t"} function abs(v) {return v < 0 ? -v : v}; /^@/ || ($7 == "="  && ($2 == 81 || $2 == 161|| $2 == 97 || $2 == 145 || $2 ==99 || $2 == 147 || $2 == 83 || $2 ==163) && abs($9) <= 2000 && abs($9) >= 38 && $5 >=20 ) {print}' # need update from config, for cleanBam
chrM: chrM  # Name of mitochondria in genome.fa, have to be exact match, this will be removed 


# Filters for bamCoverage, plotFingerprint, multiBamSummary
BIN_SIZE: 2000 # For plotFingerprint, multiBamSummary, 2000 for mouse ATAC-seq
MQ_MIN: 0 # multiBamSummary, plotFingerprint
minFragmentLength: 50  # 100 for mono-nucleosome
maxFragmentLength: 1000 # 200 for mono-nucleosome ATACseq fragments

